version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    ports:
      - "1433:1433"  
    environment:
      SA_PASSWORD: "Password123!"  
      ACCEPT_EULA: "Y"  
    volumes:
      - sqlserver_data:/var/opt/mssql 
      - ./init-sql:/docker-entrypoint-initdb.d  

volumes:
  sqlserver_data:
    driver: local
